name: GitHub Actions dev
run-name: ${{ github.actor }} is dev updated
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
jobs:

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: project_dependencies-${{ hashFiles('**/package-lock.json') }}
      - name: Install modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Run tests
        run: echo tests no detected

  build_dev:
    runs-on: ubuntu-latest
    needs: [tests]
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: project_dependencies-${{ hashFiles('**/package-lock.json') }}
      - name: Install modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build dev
        run: npm run build_dev
      - name: Create dev Artifacts 
        uses: actions/upload-artifact@v1
        with:
          name: dev
          path: dist/dev
      - name: Build final
        run: npm run build_final
      - name: Create final Artifacts 
        uses: actions/upload-artifact@v1
        with:
          name: final
          path: dist/final
      - name: Save build
      uses: actions/cache/save@v3
      with:
        path: ~/test-repo
        key: asdf

  deploy_dev:
    runs-on: ubuntu-latest
    needs: [build_dev]
    steps:
      - uses: actions/checkout@v3
      - name: Restore cached Primes
        id: cache-primes-restore
        uses: actions/cache/restore@v3
        with:
          path: ~/test-repo
          key: asdf
      - name: Deploy dev
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-page-preview
          clean: true
          folder: dist/dev
          target-folder: dist/dev