name: GitHub Actions main
run-name: ${{ github.actor }} is main updated
on:
  pull_request:
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install modules
        run: npm i

      - name: Build dev
        run: npm run build_dev

      - name: Create dev Artifacts 
        uses: actions/upload-artifact@v1
        with:
          name: dev
          path: dist/dev

      - name: Build final
        run: npm run build_final

      - name: Create final Artifacts 
        uses: actions/upload-artifact@v1
        with:
          name: final
          path: dist/final

