name: GitHub Actions dev
run-name: Dev updated
on:
  push:
    branches: [dev]
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install modules
        run: npm i

      - name: Build dev
        run: npm run build_dev

      - name: Create dev Artifacts 
        uses: actions/upload-artifact@v1
        with:
          name: dev
          path: dist/dev

      - name: Build final
        run: npm run build_final

      - name: Create final Artifacts 
        uses: actions/upload-artifact@v1
        with:
          name: final
          path: dist/final

      - name: Deploy dev
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-page-preview
          clean: true
          folder: dist/dev
          target-folder: dist/dev

      - name: Git version
        id: version
        uses: codacy/git-version@2.7.1
        with:
          prefix: "prefix"
          major-identifier: "1"
          minor-identifier: "2"
          dev-branch: dev
          release-branch: main

      - name: version
        run: echo ${{ steps.version.outputs.version }}

